sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: WP_VERSION=latest # COVERAGE=yes
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.6
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=nightly
    - php: 5.6
      env: WP_TRAVISCI=phpcs
  allow_failures:
    - php: 5.6
      env: WP_TRAVISCI=phpcs

install:
  - composer install --no-interaction

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      composer test:plugin:unit && bash <(curl -s https://codecov.io/bash) -cF unittests
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      phpcs --standard=phpcs.ruleset.xml $(find src tests -name '*.php')
    fi

after_success:
  - if [[ "$COVERAGE" == "yes" ]]; then bash <(curl -s https://codecov.io/bash) -cF integration; fi
